In [ ]:
from google.colab import files
uploaded = files.upload()

Saving student_marks.csv to student_marks.csv

In [ ]:
import pandas as pd
df = pd.read_csv("student_marks.csv")
df.head()

,Unnamed: 0,Gender,DOB,Maths,Physics,Chemistry,English,Biology,Economics,History,Civics,Total
0,John,M,05-04-1988,55,45,56,87,21,52,89,65,470
1,Suresh,M,04-05-1987,75,96,78,64,90,61,58,2,524
2,Ramesh,M,25-05-1989,25,54,89,76,95,87,56,74,556
3,Jessica,F,12-08-1990,78,96,86,63,54,89,75,45,586
4,Jennifer,F,02-09-1989,58,96,78,46,96,77,83,53,587

In [ ]:
average_marks = df["Total"].mean()
print("Average Marks:", average_marks)

Average Marks: 544.5

In [ ]:
slow_learners = df[df["Total"] < average_marks]
slow_learners

,Unnamed: 0,Gender,DOB,Maths,Physics,Chemistry,English,Biology,Economics,History,Civics,Total
0,John,M,05-04-1988,55,45,56,87,21,52,89,65,470
1,Suresh,M,04-05-1987,75,96,78,64,90,61,58,2,524
6,pooja,F,04-05-1987,55,64,61,58,75,58,64,61,496
7,Ritesh,M,25-05-1989,54,76,87,56,25,56,76,87,517

In [ ]:
fast_learners = df[df["Total"] > average_marks]
fast_learners

,Unnamed: 0,Gender,DOB,Maths,Physics,Chemistry,English,Biology,Economics,History,Civics,Total
2,Ramesh,M,25-05-1989,25,54,89,76,95,87,56,74,556
3,Jessica,F,12-08-1990,78,96,86,63,54,89,75,45,586
4,Jennifer,F,02-09-1989,58,96,78,46,96,77,83,53,587
5,Annu,F,05-04-1988,45,87,52,89,55,89,87,52,556
8,Farha,F,12-08-1990,55,63,89,75,78,75,63,89,587
9,Mukesh,M,02-09-1989,96,46,77,83,58,83,46,77,566

In [ ]:
top_students = df.sort_values(by="Total", ascending=False).head(5)
top_students

,Unnamed: 0,Gender,DOB,Maths,Physics,Chemistry,English,Biology,Economics,History,Civics,Total
8,Farha,F,12-08-1990,55,63,89,75,78,75,63,89,587
4,Jennifer,F,02-09-1989,58,96,78,46,96,77,83,53,587
3,Jessica,F,12-08-1990,78,96,86,63,54,89,75,45,586
9,Mukesh,M,02-09-1989,96,46,77,83,58,83,46,77,566
5,Annu,F,05-04-1988,45,87,52,89,55,89,87,52,556

In [ ]:
average = df["Total"].mean()
best = df.loc[df["Total"].idxmax()]
best

Unnamed: 0      Jennifer
Gender                 F
DOB           02-09-1989
Maths                 58
Physics               96
Chemistry             78
English               46
Biology               96
Economics             77
History               83
Civics                53
Total                587
Name: 4, dtype: object

In [ ]:
average = df["Total"].mean()
worst = df.loc[df["Total"].idxmin()]
worst

Unnamed: 0          John
Gender                 M
DOB           05-04-1988
Maths                 55
Physics               45
Chemistry             56
English               87
Biology               21
Economics             52
History               89
Civics                65
Total                470
Name: 0, dtype: object